<a href="https://colab.research.google.com/github/Nihcas001/data_analysis_using_Python/blob/main/07(C)_Supermarket_Analysis_using_Pandas/supermarket_analysis_using_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part 1 — Load and Understand the Dataset**

**Step 1: Import Pandas**

In [1]:
import pandas as pd  # Import Pandas for data analysis

**Step 2: Load the CSV File**

In [2]:
# Load the supermarket sales dataset
df = pd.read_csv("supermarket_sales_analysis.csv")

# Display the dataset
df

,Sale_ID,Date,Store,Category,Product,Quantity,Unit_Price,Sales_Amount
0,1001,2026-01-05,Delhi,Grocery,Rice,10,55,550
1,1002,2026-01-07,Mumbai,Beverages,Juice,8,80,640
2,1003,2026-01-10,Chandigarh,Personal Care,Shampoo,5,120,600
3,1004,2026-01-12,Delhi,Grocery,Wheat Flour,12,45,540
4,1005,2026-01-15,Pune,Dairy,Milk,15,60,900
5,1006,2026-01-18,Mumbai,Beverages,Soft Drink,20,50,1000
6,1007,2026-01-20,Chandigarh,Grocery,Sugar,9,48,432
7,1008,2026-01-23,Delhi,Personal Care,Toothpaste,7,90,630
8,1009,2026-01-25,Pune,Dairy,Curd,10,70,700
9,1010,2026-01-28,Mumbai,Grocery,Cooking Oil,6,150,900
10,1011,2026-02-02,Delhi,Beverages,Tea,12,220,2640
11,1012,2026-02-05,Chandigarh,Dairy,Butter,8,75,600
12,1013,2026-02-08,Mumbai,Grocery,Biscuits,25,30,750
13,1014,2026-02-11,Pune,Personal Care,Face Wash,6,180,1080
14,1015,2026-02-14,Delhi,Grocery,Rice,14,55,770
15,1016,2026-02-17,Mumbai,Beverages,Coffee,10,250,2500
16,1017,2026-02-20,Chandigarh,Dairy,Milk,18,60,1080
17,1018,2026-02-23,Pune,Grocery,Pulses,9,110,990
18,1019,2026-02-26,Delhi,Personal Care,Soap,20,35,700
19,1020,2026-02-28,Mumbai,Beverages,Juice,15,80,1200
20,1021,2026-03-03,Chandigarh,Grocery,Sugar,11,48,528
21,1022,2026-03-06,Delhi,Dairy,Cheese,7,300,2100
22,1023,2026-03-09,Pune,Beverages,Soft Drink,18,50,900
23,1024,2026-03-12,Mumbai,Grocery,Cooking Oil,8,150,1200
24,1025,2026-03-15,Delhi,Personal Care,Shampoo,6,120,720
25,1026,2026-03-18,Chandigarh,Dairy,Curd,12,70,840
26,1027,2026-03-21,Mumbai,Grocery,Biscuits,30,30,900
27,1028,2026-03-24,Pune,Beverages,Tea,14,220,3080
28,1029,2026-03-27,Delhi,Grocery,Wheat Flour,10,45,450
29,1030,2026-03-30,Mumbai,Personal Care,Toothpaste,9,90,810

**Step 3: Understand the Dataset**

In [3]:
# Display the first five rows
df.head()

,Sale_ID,Date,Store,Category,Product,Quantity,Unit_Price,Sales_Amount
0,1001,2026-01-05,Delhi,Grocery,Rice,10,55,550
1,1002,2026-01-07,Mumbai,Beverages,Juice,8,80,640
2,1003,2026-01-10,Chandigarh,Personal Care,Shampoo,5,120,600
3,1004,2026-01-12,Delhi,Grocery,Wheat Flour,12,45,540
4,1005,2026-01-15,Pune,Dairy,Milk,15,60,900

In [4]:
# Display the last five rows
df.tail()

,Sale_ID,Date,Store,Category,Product,Quantity,Unit_Price,Sales_Amount
25,1026,2026-03-18,Chandigarh,Dairy,Curd,12,70,840
26,1027,2026-03-21,Mumbai,Grocery,Biscuits,30,30,900
27,1028,2026-03-24,Pune,Beverages,Tea,14,220,3080
28,1029,2026-03-27,Delhi,Grocery,Wheat Flour,10,45,450
29,1030,2026-03-30,Mumbai,Personal Care,Toothpaste,9,90,810

In [5]:
# Display number of rows and columns
df.shape

(30, 8)

**Step 4: Check Data Types**

In [6]:
# Display column names, data types, and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sale_ID       30 non-null     int64
 1   Date          30 non-null     object
 2   Store         30 non-null     object
 3   Category      30 non-null     object
 4   Product       30 non-null     object
 5   Quantity      30 non-null     int64
 6   Unit_Price    30 non-null     int64
 7   Sales_Amount  30 non-null     int64
dtypes: int64(4), object(4)
memory usage: 2.0+ KB

**Part 2 — What is Grouping?**

Suppose the supermarket manager asks:

>How much total sales did each category generate?

Our dataset contains many transactions:
```
Grocery
Beverages
Grocery
Dairy
Beverages
Grocery
...
```
Instead of manually calculating each category, Pandas can group the records according to Category.

The main function is:

`groupby()`

**Step 5: Basic groupby()**

In [12]:
# Group sales records according to product category
category_group = df.groupby("Category")

# Display the grouped object
print(category_group)

               Sale_ID  Date  Store  Product  Quantity  Unit_Price  \
Category
Beverages            7     7      7        7         7           7
Dairy                6     6      6        6         6           6
Grocery             11    11     11       11        11          11
Personal Care        6     6      6        6         6           6

               Sales_Amount
Category
Beverages                 7
Dairy                     6
Grocery                  11
Personal Care             6

The result is a GroupBy object.

It does not perform a calculation yet.

We need to tell Pandas what calculation we want.

**Part 3 — Aggregation
What is Aggregation?**

Aggregation means:

> Summarizing multiple records into a single value.

Common aggregation functions are:
```
Function	Meaning
sum()	    Total
mean()	    Average
count()	    Number of records
min()	    Minimum
max()	    Maximum
median()	Middle value
```

**Step 6: Total Sales by Category**

This is the most important operation for this problem.

In [13]:
# Calculate total sales for each category
category_sales = df.groupby("Category")["Sales_Amount"].sum()

# Display total sales by category
category_sales

Category
Beverages        11960
Dairy             6220
Grocery           8010
Personal Care     4540
Name: Sales_Amount, dtype: int64

**Conceptually**:

```
Category
    ↓
Group records
    ↓
Sales_Amount
    ↓
Calculate SUM
```

**Step 7: Total Quantity Sold by Category**

We can also calculate the total number of units sold.

In [16]:
# Calculate total quantity sold in each category
category_quantity = df.groupby("Category")["Quantity"].sum()

# Display the result
category_quantity

Category
Beverages         97
Dairy             70
Grocery          144
Personal Care     53
Name: Quantity, dtype: int64

**Step 8: Average Sales by Category**

Instead of total sales, suppose the manager wants the average transaction value.

In [17]:
# Calculate average sales amount for each category
average_sales = df.groupby("Category")["Sales_Amount"].mean()

# Display average sales
average_sales

Category
Beverages        1708.571429
Dairy            1036.666667
Grocery           728.181818
Personal Care     756.666667
Name: Sales_Amount, dtype: float64

**Step 9: Number of Transactions per Category**

We can use *count()*.

In [18]:
# Count the number of sales transactions in each category
category_count = df.groupby("Category")["Sale_ID"].count()

# Display transaction count
category_count

Category
Beverages         7
Dairy             6
Grocery          11
Personal Care     6
Name: Sale_ID, dtype: int64

**Step 10: Minimum Sales by Category**

In [19]:
# Find the minimum transaction value for each category
minimum_sales = df.groupby("Category")["Sales_Amount"].min()

# Display minimum sales
minimum_sales

Category
Beverages        640
Dairy            600
Grocery          432
Personal Care    600
Name: Sales_Amount, dtype: int64

**Step 11: Maximum Sales by Category**

In [20]:
# Find the maximum transaction value for each category
maximum_sales = df.groupby("Category")["Sales_Amount"].max()

# Display maximum sales
maximum_sales

Category
Beverages        3080
Dairy            2100
Grocery          1200
Personal Care    1080
Name: Sales_Amount, dtype: int64

**Part 4 — Multiple Aggregations**

A very useful Pandas feature is performing multiple aggregations at once.

Suppose the supermarket manager wants:

*   Total sales
*   Average sales
*   Minimum sales
*   Maximum sales

for every category.

We can use **.agg().**

**Step 12: Multiple Aggregations**

In [21]:
# Calculate multiple sales statistics for each category
category_summary = df.groupby("Category")["Sales_Amount"].agg(
    ["sum", "mean", "min", "max"]
)

# Display the category-wise summary
category_summary

                 sum         mean  min   max
Category
Beverages      11960  1708.571429  640  3080
Dairy           6220  1036.666667  600  2100
Grocery         8010   728.181818  432  1200
Personal Care   4540   756.666667  600  1080

**Part 5 — Named Aggregations**

We can give meaningful names to the output columns.

In [22]:
# Create a readable category-wise sales summary
category_summary = df.groupby("Category").agg(
    Total_Sales=("Sales_Amount", "sum"),
    Average_Sales=("Sales_Amount", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Transactions=("Sale_ID", "count")
)

# Display the summary
category_summary

               Total_Sales  Average_Sales  Total_Quantity  Transactions
Category
Beverages            11960    1708.571429              97             7
Dairy                 6220    1036.666667              70             6
Grocery               8010     728.181818             144            11
Personal Care         4540     756.666667              53             6

**Part 6 — Grouping by Multiple Columns**

We can group data using more than one column.

For example:

> Find total sales for every category in every store.

We need:

`Store + Category`

**Step 13: Group by Store and Category**

In [23]:
# Calculate total sales for each store-category combination
store_category_sales = df.groupby(
    ["Store", "Category"]
)["Sales_Amount"].sum()

# Display the result
store_category_sales

Store       Category
Chandigarh  Dairy            2520
            Grocery           960
            Personal Care     600
Delhi       Beverages        2640
            Dairy            2100
            Grocery          2310
            Personal Care    2050
Mumbai      Beverages        5340
            Grocery          3750
            Personal Care     810
Pune        Beverages        3980
            Dairy            1600
            Grocery           990
            Personal Care    1080
Name: Sales_Amount, dtype: int64

**Step 14: Convert Grouped Result into a DataFrame**

Sometimes we want the result in normal tabular form.

Use:

**`reset_index()`**

In [24]:
# Convert the grouped result back into a DataFrame
store_category_sales = df.groupby(
    ["Store", "Category"]
)["Sales_Amount"].sum().reset_index()

# Display the result
store_category_sales

         Store       Category  Sales_Amount
0   Chandigarh          Dairy          2520
1   Chandigarh        Grocery           960
2   Chandigarh  Personal Care           600
3        Delhi      Beverages          2640
4        Delhi          Dairy          2100
5        Delhi        Grocery          2310
6        Delhi  Personal Care          2050
7       Mumbai      Beverages          5340
8       Mumbai        Grocery          3750
9       Mumbai  Personal Care           810
10        Pune      Beverages          3980
11        Pune          Dairy          1600
12        Pune        Grocery           990
13        Pune  Personal Care          1080

**Part 7 — Sorting Grouped Results**

Suppose we want to find which category generated the highest sales.

In [25]:
# Calculate total sales by category
category_sales = df.groupby("Category")["Sales_Amount"].sum()

# Sort categories from highest to lowest sales
category_sales = category_sales.sort_values(ascending=False)

# Display the sorted result
category_sales

Category
Beverages        11960
Grocery           8010
Dairy             6220
Personal Care     4540
Name: Sales_Amount, dtype: int64

**Step 15: Find the Highest-Selling Category**

idxmax() returns the index/label corresponding to the maximum value.

In [26]:
# Find the category with the highest total sales
highest_category = category_sales.idxmax()

# Display the category name
print("Highest-selling category:", highest_category)

Highest-selling category: Beverages

**Part 8 — What is a Pivot Table?**

A pivot table is a powerful way of summarizing data from different dimensions.

Suppose the supermarket manager asks:

> Show me sales for each category across different stores.

We can create:

| Category      | Chandigarh | Delhi | Mumbai | Pune |
| ------------- | ---------: | ----: | -----: | ---: |
| Beverages     |        ... |   ... |    ... |  ... |
| Dairy         |        ... |   ... |    ... |  ... |
| Grocery       |        ... |   ... |    ... |  ... |
| Personal Care |        ... |   ... |    ... |  ... |


This is exactly what a pivot table is useful for.

**Step 16 — Basic Pivot Table**

The Pandas function is:

`pd.pivot_table()`

In [28]:
# Create a pivot table showing category-wise sales by store
pivot_sales = pd.pivot_table(
    df,                    # The source DataFrame
    values="Sales_Amount", # The numerical column we want to analyze.
    index="Category",      # The rows of the pivot table.
    columns="Store",       # The columns of the pivot table.
    aggfunc="sum"          # The calculation to perform.
)

# Display the pivot table
pivot_sales

Store          Chandigarh   Delhi  Mumbai    Pune
Category
Beverages             NaN  2640.0  5340.0  3980.0
Dairy              2520.0  2100.0     NaN  1600.0
Grocery             960.0  2310.0  3750.0   990.0
Personal Care       600.0  2050.0   810.0  1080.0

**Step 17 — Pivot Table Using Average**

Instead of total sales, we can calculate average sales.

In [29]:
# Create a pivot table showing average sales by category and store
pivot_average = pd.pivot_table(
    df,
    values="Sales_Amount",
    index="Category",
    columns="Store",
    aggfunc="mean"
)

# Display the pivot table
pivot_average

Store          Chandigarh        Delhi  Mumbai    Pune
Category
Beverages             NaN  2640.000000  1335.0  1990.0
Dairy               840.0  2100.000000     NaN   800.0
Grocery             480.0   577.500000   937.5   990.0
Personal Care       600.0   683.333333   810.0  1080.0

**Step 18 — Pivot Table Using Quantity**

We can analyze quantity instead of sales.

In [30]:
# Create a pivot table showing total quantity sold by category and store
pivot_quantity = pd.pivot_table(
    df,
    values="Quantity",
    index="Category",
    columns="Store",
    aggfunc="sum"
)

# Display the pivot table
pivot_quantity

Store          Chandigarh  Delhi  Mumbai  Pune
Category
Beverages             NaN   12.0    53.0  32.0
Dairy                38.0    7.0     NaN  25.0
Grocery              20.0   46.0    69.0   9.0
Personal Care         5.0   33.0     9.0   6.0

**Step 19 — Add Total Row and Column**

A pivot table can automatically calculate totals using **margins=True.**

In [31]:
# Create a pivot table with category-store totals
pivot_total = pd.pivot_table(
    df,
    values="Sales_Amount",
    index="Category",
    columns="Store",
    aggfunc="sum",
    margins=True
)

# Display category, store, and grand totals
pivot_total

Store          Chandigarh   Delhi  Mumbai    Pune    All
Category
Beverages             NaN  2640.0  5340.0  3980.0  11960
Dairy              2520.0  2100.0     NaN  1600.0   6220
Grocery             960.0  2310.0  3750.0   990.0   8010
Personal Care       600.0  2050.0   810.0  1080.0   4540
All                4080.0  9100.0  9900.0  7650.0  30730

**Step 20 — Replace Missing Pivot Values**

Some category-store combinations may not exist in the dataset.

These can appear as **NaN**.

We can replace them with zero.

In [32]:
# Replace missing pivot table values with zero
pivot_sales = pivot_sales.fillna(0)

# Display the cleaned pivot table
pivot_sales

Store          Chandigarh   Delhi  Mumbai    Pune
Category
Beverages             0.0  2640.0  5340.0  3980.0
Dairy              2520.0  2100.0     0.0  1600.0
Grocery             960.0  2310.0  3750.0   990.0
Personal Care       600.0  2050.0   810.0  1080.0

**Part 9 — Grouping by Month**

Since our dataset contains dates, we can also perform monthly sales analysis.

First, make sure the Date column is a datetime column.

In [33]:
# Convert the Date column into Pandas datetime format
df["Date"] = pd.to_datetime(df["Date"])

**Step 21: Extract Month**

In [40]:
# Extract the month from each sale date
df["Month"] = df["Date"].dt.month

# Display the first few records
df[["Date", "Month"]].head()

        Date  Month
0 2026-01-05      1
1 2026-01-07      1
2 2026-01-10      1
3 2026-01-12      1
4 2026-01-15      1

**Step 22: Monthly Sales**

In [35]:
# Calculate total sales for each month
monthly_sales = df.groupby("Month")["Sales_Amount"].sum()

# Display monthly sales
monthly_sales

Month
1     6892
2    12310
3    11528
Name: Sales_Amount, dtype: int64

**Step 23 — Month and Category Analysis**

We can combine multiple dimensions.

In [41]:
# Calculate monthly sales for each category
monthly_category_sales = df.groupby(
    ["Month", "Category"]
)["Sales_Amount"].sum().reset_index()

# Display the result
monthly_category_sales

    Month       Category  Sales_Amount
0       1      Beverages          1640
1       1          Dairy          1600
2       1        Grocery          2422
3       1  Personal Care          1230
4       2      Beverages          6340
5       2          Dairy          1680
6       2        Grocery          2510
7       2  Personal Care          1780
8       3      Beverages          3980
9       3          Dairy          2940
10      3        Grocery          3078
11      3  Personal Care          1530

**Step 24 — Monthly Category Pivot Table**

This can be represented more clearly using a pivot table.

In [42]:
# Create a pivot table for monthly category-wise sales
monthly_pivot = pd.pivot_table(
    df,
    values="Sales_Amount",
    index="Month",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)

# Display the monthly sales analysis
monthly_pivot

Category  Beverages  Dairy  Grocery  Personal Care
Month
1              1640   1600     2422           1230
2              6340   1680     2510           1780
3              3980   2940     3078           1530

**Part 10 — Complete Category-Wise Analysis**

Now let's create one complete analysis that a supermarket manager could actually use.

This is a strong example of grouping + aggregation + sorting.

In [43]:
# Generate a complete category-wise sales summary
category_analysis = df.groupby("Category").agg(
    Total_Sales=("Sales_Amount", "sum"),
    Average_Sale=("Sales_Amount", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Number_of_Transactions=("Sale_ID", "count"),
    Maximum_Sale=("Sales_Amount", "max"),
    Minimum_Sale=("Sales_Amount", "min")
)

# Sort categories by total sales
category_analysis = category_analysis.sort_values(
    "Total_Sales",
    ascending=False
)

# Display the final category analysis
category_analysis

,Total_Sales,Average_Sale,Total_Quantity,Number_of_Transactions,Maximum_Sale,Minimum_Sale
Category,,,,,,
Beverages,11960,1708.571429,97,7,3080,640
Grocery,8010,728.181818,144,11,1200,432
Dairy,6220,1036.666667,70,6,2100,600
Personal Care,4540,756.666667,53,6,1080,600

**Part 11 — Complete Pivot Analysis**

In [44]:
# Create a category-store sales pivot table
category_store_pivot = pd.pivot_table(
    df,
    values="Sales_Amount",
    index="Category",
    columns="Store",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

# Display the final pivot analysis
category_store_pivot

Store          Chandigarh  Delhi  Mumbai  Pune    All
Category
Beverages               0   2640    5340  3980  11960
Dairy                2520   2100       0  1600   6220
Grocery               960   2310    3750   990   8010
Personal Care         600   2050     810  1080   4540
All                  4080   9100    9900  7650  30730

This lets the supermarket answer questions such as:

* Which category has the highest sales?
* Which store generates the highest sales?
* How much does each category contribute to each store?
* Which category performs poorly at a particular store?
* What is the overall sales total?