<a href="https://colab.research.google.com/github/Nihcas001/data_analysis_using_Python/blob/main/07(B)_Survey_Analysis_using_Pandas/Survey_using_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd  # Import Pandas for data manipulation

In [34]:
# Load the first feedback dataset
df = pd.read_csv("customer_feedback_batch1.csv")

# Display the dataset
df

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,1001,Aman Sharma,24.0,Delhi,5.0,Excellent service,Online
1,1002,Priya Singh,29.0,delhi,4.0,good service,online
2,1003,Rahul Kumar,NaN,Mumbai,NaN,NaN,Mobile App
3,1004,Simran Kaur,35.0,MUMBAI,3.0,Average,Web
4,1005,Karan Mehta,41.0,Chandigarh,5.0,Excellent,NaN
5,1006,Neha Verma,27.0,Chandigarh,4.0,Very good,Mobile app
6,1007,Arjun Patel,32.0,Pune,2.0,poor delivery,Phone
7,1008,Riya Gupta,NaN,NaN,NaN,Good,Online
8,1009,Vikas Singh,45.0,Delhi,5.0,NaN,Web
9,1010,Anjali Rao,26.0,pune,4.0,good,online
10,1011,Mohit Sharma,31.0,Mumbai,3.0,Average service,Phone
11,1012,Pooja Verma,38.0,Delhi,NaN,Excellent service,NaN
12,1013,Rohit Kumar,NaN,Chandigarh,4.0,Good,Web
13,1014,Sneha Singh,23.0,PUNE,5.0,NaN,Mobile App
14,1015,Varun Mehta,36.0,Delhi,3.0,Poor,phone
15,1016,Kavya Rao,28.0,Mumbai,NaN,Very Good,Online
16,1017,Aditya Patel,NaN,NaN,2.0,poor,Web
17,1018,Nisha Gupta,42.0,Delhi,5.0,Excellent,NaN
18,1019,Manish Kumar,34.0,mumbai,4.0,Good service,Mobile app
19,1020,Tanya Sharma,25.0,Chandigarh,3.0,NaN,Online

**Inspect the Dataset**

Before cleaning data, we should understand it.

In [35]:
# Display the first five rows
df.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,1001,Aman Sharma,24.0,Delhi,5.0,Excellent service,Online
1,1002,Priya Singh,29.0,delhi,4.0,good service,online
2,1003,Rahul Kumar,NaN,Mumbai,NaN,NaN,Mobile App
3,1004,Simran Kaur,35.0,MUMBAI,3.0,Average,Web
4,1005,Karan Mehta,41.0,Chandigarh,5.0,Excellent,NaN

In [36]:
# Display the last five rows
df.tail()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
15,1016,Kavya Rao,28.0,Mumbai,NaN,Very Good,Online
16,1017,Aditya Patel,NaN,NaN,2.0,poor,Web
17,1018,Nisha Gupta,42.0,Delhi,5.0,Excellent,NaN
18,1019,Manish Kumar,34.0,mumbai,4.0,Good service,Mobile app
19,1020,Tanya Sharma,25.0,Chandigarh,3.0,NaN,Online

In [37]:
# Display number of rows and columns
df.shape

(20, 7)

**Check Column Names**

In [38]:
# Display all column names
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'City', 'Rating', 'Feedback',
       'Response_Channel'],
      dtype='object')

**Check Data Types**

In [39]:
# Display data types and non-null information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       20 non-null     int64
 1   Customer_Name     20 non-null     object
 2   Age               16 non-null     float64
 3   City              18 non-null     object
 4   Rating            16 non-null     float64
 5   Feedback          16 non-null     object
 6   Response_Channel  17 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.2+ KB

**PART A — HANDLING MISSING DATA**

**What is Missing Data?**

Missing data means that some values are unavailable.

In real-world datasets, missing data can occur because:
```
Customer skipped a question
Form was incomplete
Data was not recorded
Technical problem occurred
Information was unavailable
```

Detect Missing Values

Pandas provides:

`isnull()`

In [40]:
# Check which values are missing
df.isnull()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,True,False,True,True,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,True,True,True,False,False
8,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,True,False,True
12,False,False,True,False,False,False,False
13,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False
16,False,False,True,True,False,False,False
17,False,False,False,False,False,False,True
18,False,False,False,False,False,False,False
19,False,False,False,False,False,True,False

This produces True and False.

True  → Missing

False → Not missing

**Count Missing Values**

In [41]:
# Count missing values in each column
df.isnull().sum()

Customer_ID         0
Customer_Name       0
Age                 4
City                2
Rating              4
Feedback            4
Response_Channel    3
dtype: int64

**Find Rows Having Missing Values**

In [42]:
# Display rows containing at least one missing value
df[df.isnull().any(axis=1)]

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
2,1003,Rahul Kumar,NaN,Mumbai,NaN,NaN,Mobile App
4,1005,Karan Mehta,41.0,Chandigarh,5.0,Excellent,NaN
7,1008,Riya Gupta,NaN,NaN,NaN,Good,Online
8,1009,Vikas Singh,45.0,Delhi,5.0,NaN,Web
11,1012,Pooja Verma,38.0,Delhi,NaN,Excellent service,NaN
12,1013,Rohit Kumar,NaN,Chandigarh,4.0,Good,Web
13,1014,Sneha Singh,23.0,PUNE,5.0,NaN,Mobile App
15,1016,Kavya Rao,28.0,Mumbai,NaN,Very Good,Online
16,1017,Aditya Patel,NaN,NaN,2.0,poor,Web
17,1018,Nisha Gupta,42.0,Delhi,5.0,Excellent,NaN
19,1020,Tanya Sharma,25.0,Chandigarh,3.0,NaN,Online

Understanding:
`any(axis=1)`

means:

>Check each row and determine whether at least one value is missing.

**Find Complete Records**

Sometimes we want only records where no values are missing.

In [43]:
# Select rows that contain no missing values
complete_df = df.dropna()

# Display complete records
complete_df

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,1001,Aman Sharma,24.0,Delhi,5.0,Excellent service,Online
1,1002,Priya Singh,29.0,delhi,4.0,good service,online
3,1004,Simran Kaur,35.0,MUMBAI,3.0,Average,Web
5,1006,Neha Verma,27.0,Chandigarh,4.0,Very good,Mobile app
6,1007,Arjun Patel,32.0,Pune,2.0,poor delivery,Phone
9,1010,Anjali Rao,26.0,pune,4.0,good,online
10,1011,Mohit Sharma,31.0,Mumbai,3.0,Average service,Phone
14,1015,Varun Mehta,36.0,Delhi,3.0,Poor,phone
18,1019,Manish Kumar,34.0,mumbai,4.0,Good service,Mobile app

**Remove Rows with Missing Values**

dropna() removes rows containing missing values.

In [44]:
# Remove rows containing any missing value
df_clean = df.dropna()

# Display the cleaned dataset
df_clean

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,1001,Aman Sharma,24.0,Delhi,5.0,Excellent service,Online
1,1002,Priya Singh,29.0,delhi,4.0,good service,online
3,1004,Simran Kaur,35.0,MUMBAI,3.0,Average,Web
5,1006,Neha Verma,27.0,Chandigarh,4.0,Very good,Mobile app
6,1007,Arjun Patel,32.0,Pune,2.0,poor delivery,Phone
9,1010,Anjali Rao,26.0,pune,4.0,good,online
10,1011,Mohit Sharma,31.0,Mumbai,3.0,Average service,Phone
14,1015,Varun Mehta,36.0,Delhi,3.0,Poor,phone
18,1019,Manish Kumar,34.0,mumbai,4.0,Good service,Mobile app

**But there is a problem**

If the dataset has many missing values, dropna() may remove too many useful records.

Therefore, sometimes we should fill missing values instead of deleting them.

**Fill Missing Age with Mean**

In [45]:
# Calculate the average age
mean_age = df["Age"].mean()

# Fill missing ages with the average age
df["Age"] = df["Age"].fillna(mean_age)

# Display the updated Age column
df["Age"]

0     24.00
1     29.00
2     32.25
3     35.00
4     41.00
5     27.00
6     32.00
7     32.25
8     45.00
9     26.00
10    31.00
11    38.00
12    32.25
13    23.00
14    36.00
15    28.00
16    32.25
17    42.00
18    34.00
19    25.00
Name: Age, dtype: float64

**Fill Missing Rating with Median**

For ratings, median can be useful because it is less affected by extreme values.

In [46]:
# Calculate the median rating
median_rating = df["Rating"].median()

# Fill missing ratings with the median
df["Rating"] = df["Rating"].fillna(median_rating)

df["Rating"]

0     5.0
1     4.0
2     4.0
3     3.0
4     5.0
5     4.0
6     2.0
7     4.0
8     5.0
9     4.0
10    3.0
11    4.0
12    4.0
13    5.0
14    3.0
15    4.0
16    2.0
17    5.0
18    4.0
19    3.0
Name: Rating, dtype: float64

**Fill Missing City**

For categorical data such as City, mean or median doesn't make sense.

We can use the **mode**.

Mode means:

>The value that occurs most frequently.

In [47]:
# Find the most frequently occurring city
mode_city = df["City"].mode()[0]

# Fill missing cities with the most common city
df["City"] = df["City"].fillna(mode_city)

df["City"]

0           Delhi
1           delhi
2          Mumbai
3          MUMBAI
4      Chandigarh
5     Chandigarh
6            Pune
7           Delhi
8           Delhi
9            pune
10         Mumbai
11          Delhi
12     Chandigarh
13           PUNE
14          Delhi
15         Mumbai
16          Delhi
17          Delhi
18         mumbai
19     Chandigarh
Name: City, dtype: object

**Fill Missing Feedback**

For text fields, we can use a meaningful label.

In [48]:
# Replace missing feedback with a descriptive label
df["Feedback"] = df["Feedback"].fillna("No feedback provided")
df["Feedback"]

0        Excellent service
1             good service
2     No feedback provided
3                  Average
4                Excellent
5                Very good
6            poor delivery
7                     Good
8     No feedback provided
9                     good
10         Average service
11       Excellent service
12                    Good
13    No feedback provided
14                    Poor
15               Very Good
16                    poor
17               Excellent
18            Good service
19    No feedback provided
Name: Feedback, dtype: object

**Fill Missing Response Channel**

In [49]:
# Replace missing response channels with an appropriate label
df["Response_Channel"] = df["Response_Channel"].fillna("Unknown")
df["Response_Channel"]

0         Online
1         online
2     Mobile App
3            Web
4        Unknown
5     Mobile app
6          Phone
7         Online
8            Web
9         online
10         Phone
11       Unknown
12           Web
13    Mobile App
14         phone
15        Online
16           Web
17       Unknown
18    Mobile app
19        Online
Name: Response_Channel, dtype: object

**Check Missing Values Again**

In [50]:
# Check whether any missing values remain
df.isnull().sum()

Customer_ID         0
Customer_Name       0
Age                 0
City                0
Rating              0
Feedback            0
Response_Channel    0
dtype: int64

**PART B — CLEANING INCONSISTENT RECORDS**

Now we have to deal with another common real-world problem.

The same city has been entered in different ways:

```
Delhi
delhi

Mumbai
MUMBAI
mumbai

Pune
pune
PUNE
```

Pandas treats these as different strings.

**Remove Extra Spaces**

In [51]:
# Remove unnecessary spaces from city names
df["City"] = df["City"].str.strip()

**Standardize Letter Case**

In [52]:
# Convert city names to lowercase
df["City"] = df["City"].str.lower()

**Convert City Names to Title Case**

For better presentation:

In [53]:
# Convert city names to title case
df["City"] = df["City"].str.title()

**Clean Response Channel**

In [54]:
# Remove spaces and standardize response channel formatting
df["Response_Channel"] = df["Response_Channel"].str.strip().str.title()

**Clean Feedback Text**

We can also standardize the feedback text.

In [55]:
# Remove extra spaces and standardize feedback capitalization
df["Feedback"] = df["Feedback"].str.strip().str.title()

**PART C — FINDING DUPLICATE RECORDS**

**What is Duplicate Data?**

A duplicate record is a record that appears more than once when it should appear only once.

In [56]:
# Check whether duplicate rows exist
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [57]:
# Count the number of duplicate rows
df.duplicated().sum()

np.int64(0)

**Remove Duplicate Records**

In [58]:
# Remove completely duplicated rows
df = df.drop_duplicates()

**Check Duplicate Customer IDs**

Sometimes the entire row isn't duplicated, but the same customer may appear multiple times.

In [59]:
# Find customers whose IDs appear more than once
duplicate_ids = df[df.duplicated("Customer_ID", keep=False)]

# Display duplicate customer records
duplicate_ids

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Age, City, Rating, Feedback, Response_Channel]
Index: []

**PART D — MERGING DATASETS**

Now let's assume the company has another dataset containing customer information.

**Load the Customer Master Dataset**

In [60]:
# Load the customer master dataset
customer_master = pd.read_csv("customer_master.csv")

# Display the first five records
customer_master.head()

   Customer_ID             Email Membership
0         1001    aman@gmail.com       Gold
1         1002   priya@gmail.com     Silver
2         1003   rahul@gmail.com       Gold
3         1004  simran@gmail.com     Silver
4         1005   karan@gmail.com       Gold

**Understand Why We Need Merge**

Before merging:

**Feedback dataset**

`Customer_ID | Customer_Name | Age | City | Rating`

Customer master

`Customer_ID | Email | Membership`

After merging:

`Customer_ID | Customer_Name | Age | City | Rating | Email | Membership`

This gives us a more complete dataset.

**Inner Merge**

The basic syntax is:

`pd.merge(left, right, on="common_column", how='inner')`

In [61]:
# Merge feedback data with customer master data using Customer_ID
merged_df = pd.merge(
    df,
    customer_master,
    on="Customer_ID",
    how="inner"
)

# Display the merged dataset
merged_df.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel,Email,Membership
0,1001,Aman Sharma,24.00,Delhi,5.0,Excellent Service,Online,aman@gmail.com,Gold
1,1002,Priya Singh,29.00,Delhi,4.0,Good Service,Online,priya@gmail.com,Silver
2,1003,Rahul Kumar,32.25,Mumbai,4.0,No Feedback Provided,Mobile App,rahul@gmail.com,Gold
3,1004,Simran Kaur,35.00,Mumbai,3.0,Average,Web,simran@gmail.com,Silver
4,1005,Karan Mehta,41.00,Chandigarh,5.0,Excellent,Unknown,karan@gmail.com,Gold

31. Understanding inner

An inner join returns only records that have matching IDs in both datasets.

Conceptually:

```
Feedback Dataset
       +
Customer Master
       ↓
Matching Customer_IDs
```

**Left Merge**

A left merge keeps all records from the left DataFrame.

In [62]:
# Keep all feedback records and add matching customer information
left_merged = pd.merge(
    df,
    customer_master,
    on="Customer_ID",
    how="left"
)

# Display the result
left_merged.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel,Email,Membership
0,1001,Aman Sharma,24.00,Delhi,5.0,Excellent Service,Online,aman@gmail.com,Gold
1,1002,Priya Singh,29.00,Delhi,4.0,Good Service,Online,priya@gmail.com,Silver
2,1003,Rahul Kumar,32.25,Mumbai,4.0,No Feedback Provided,Mobile App,rahul@gmail.com,Gold
3,1004,Simran Kaur,35.00,Mumbai,3.0,Average,Web,simran@gmail.com,Silver
4,1005,Karan Mehta,41.00,Chandigarh,5.0,Excellent,Unknown,karan@gmail.com,Gold

This is often useful when the feedback dataset is your **main dataset.**

**Right Merge**

A right merge keeps all records from the right DataFrame.

In [63]:
# Keep all customer master records during the merge
right_merged = pd.merge(
    df,
    customer_master,
    on="Customer_ID",
    how="right"
)

# Display the result
right_merged.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel,Email,Membership
0,1001,Aman Sharma,24.00,Delhi,5.0,Excellent Service,Online,aman@gmail.com,Gold
1,1002,Priya Singh,29.00,Delhi,4.0,Good Service,Online,priya@gmail.com,Silver
2,1003,Rahul Kumar,32.25,Mumbai,4.0,No Feedback Provided,Mobile App,rahul@gmail.com,Gold
3,1004,Simran Kaur,35.00,Mumbai,3.0,Average,Web,simran@gmail.com,Silver
4,1005,Karan Mehta,41.00,Chandigarh,5.0,Excellent,Unknown,karan@gmail.com,Gold

**Outer Merge**

An outer merge keeps records from both datasets.

In [64]:
# Keep all records from both datasets
outer_merged = pd.merge(
    df,
    customer_master,
    on="Customer_ID",
    how="outer"
)

# Display the merged result
outer_merged.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel,Email,Membership
0,1001,Aman Sharma,24.00,Delhi,5.0,Excellent Service,Online,aman@gmail.com,Gold
1,1002,Priya Singh,29.00,Delhi,4.0,Good Service,Online,priya@gmail.com,Silver
2,1003,Rahul Kumar,32.25,Mumbai,4.0,No Feedback Provided,Mobile App,rahul@gmail.com,Gold
3,1004,Simran Kaur,35.00,Mumbai,3.0,Average,Web,simran@gmail.com,Silver
4,1005,Karan Mehta,41.00,Chandigarh,5.0,Excellent,Unknown,karan@gmail.com,Gold

**Understand the Four Merge Types**

```
Merge	Meaning
inner	Only matching records
left	All records from left DataFrame
right	All records from right DataFrame
outer	All records from both DataFrames
```

Easy memory trick:

```
INNER → Intersection
LEFT  → Everything from LEFT
RIGHT → Everything from RIGHT
OUTER → Everything from BOTH
```

**PART E — CONCATENATING DATASETS**

**Load Batch 2**

In [65]:
# Load the second feedback batch
feedback_batch2 = pd.read_csv("customer_feedback_batch2.csv")

# Display the second batch
feedback_batch2.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,1021,Ravi Kumar,30.0,Delhi,4.0,Good,Online
1,1022,Isha Mehta,NaN,delhi,5.0,Excellent,Web
2,1023,Deepak Singh,37.0,Mumbai,3.0,Average,Mobile App
3,1024,Meena Rao,24.0,Pune,NaN,Good service,online
4,1025,Sahil Gupta,29.0,CHANDIGARH,4.0,NaN,Phone

**Concatenate Two Feedback Datasets**

Both datasets have the same columns.

Therefore, we can stack them vertically.

In [66]:
# Combine the two feedback batches row-wise
all_feedback = pd.concat(
    [df, feedback_batch2],
    ignore_index=True
)

# Display the combined dataset
all_feedback

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,1001,Aman Sharma,24.00,Delhi,5.0,Excellent Service,Online
1,1002,Priya Singh,29.00,Delhi,4.0,Good Service,Online
2,1003,Rahul Kumar,32.25,Mumbai,4.0,No Feedback Provided,Mobile App
3,1004,Simran Kaur,35.00,Mumbai,3.0,Average,Web
4,1005,Karan Mehta,41.00,Chandigarh,5.0,Excellent,Unknown
5,1006,Neha Verma,27.00,Chandigarh,4.0,Very Good,Mobile App
6,1007,Arjun Patel,32.00,Pune,2.0,Poor Delivery,Phone
7,1008,Riya Gupta,32.25,Delhi,4.0,Good,Online
8,1009,Vikas Singh,45.00,Delhi,5.0,No Feedback Provided,Web
9,1010,Anjali Rao,26.00,Pune,4.0,Good,Online
10,1011,Mohit Sharma,31.00,Mumbai,3.0,Average Service,Phone
11,1012,Pooja Verma,38.00,Delhi,4.0,Excellent Service,Unknown
12,1013,Rohit Kumar,32.25,Chandigarh,4.0,Good,Web
13,1014,Sneha Singh,23.00,Pune,5.0,No Feedback Provided,Mobile App
14,1015,Varun Mehta,36.00,Delhi,3.0,Poor,Phone
15,1016,Kavya Rao,28.00,Mumbai,4.0,Very Good,Online
16,1017,Aditya Patel,32.25,Delhi,2.0,Poor,Web
17,1018,Nisha Gupta,42.00,Delhi,5.0,Excellent,Unknown
18,1019,Manish Kumar,34.00,Mumbai,4.0,Good Service,Mobile App
19,1020,Tanya Sharma,25.00,Chandigarh,3.0,No Feedback Provided,Online
20,1021,Ravi Kumar,30.00,Delhi,4.0,Good,Online
21,1022,Isha Mehta,NaN,delhi,5.0,Excellent,Web
22,1023,Deepak Singh,37.00,Mumbai,3.0,Average,Mobile App
23,1024,Meena Rao,24.00,Pune,NaN,Good service,online
24,1025,Sahil Gupta,29.00,CHANDIGARH,4.0,NaN,Phone
25,1026,Komal Sharma,40.00,Mumbai,2.0,Poor,Mobile app
26,1027,Nitin Verma,NaN,Pune,5.0,Excellent,NaN
27,1028,Aisha Patel,33.00,NaN,3.0,Average,Web
28,1029,Gaurav Singh,27.00,Delhi,NaN,Good,Phone
29,1030,Preeti Kumar,36.00,mumbai,4.0,Very good,Online

**Important difference**

`concat()` is generally used when datasets have a similar structure and we want to stack them.

`merge()` is used when datasets have related information connected through a common key.

**PART F — FINAL DATA-CLEANING PIPELINE**

**Complete Cleaning Process**

Now let's put everything together.

In [67]:
import pandas as pd

# Load the feedback dataset
df = pd.read_csv("customer_feedback_batch1.csv")

# Remove unnecessary spaces from text columns
df["City"] = df["City"].str.strip()
df["Response_Channel"] = df["Response_Channel"].str.strip()

# Standardize city names
df["City"] = df["City"].str.title()

# Standardize response channel names
df["Response_Channel"] = df["Response_Channel"].str.title()

# Fill missing numerical values with median
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Rating"] = df["Rating"].fillna(df["Rating"].median())

# Fill missing categorical values with mode
df["City"] = df["City"].fillna(df["City"].mode()[0])

# Fill missing text values with a meaningful label
df["Feedback"] = df["Feedback"].fillna("No Feedback")
df["Response_Channel"] = df["Response_Channel"].fillna("Unknown")

# Remove duplicate records
df = df.drop_duplicates()

# Display the cleaned dataset
df.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel
0,1001,Aman Sharma,24.0,Delhi,5.0,Excellent service,Online
1,1002,Priya Singh,29.0,Delhi,4.0,good service,Online
2,1003,Rahul Kumar,31.5,Mumbai,4.0,No Feedback,Mobile App
3,1004,Simran Kaur,35.0,Mumbai,3.0,Average,Web
4,1005,Karan Mehta,41.0,Chandigarh,5.0,Excellent,Unknown

**Merge Cleaned Data with Customer Master**

In [69]:
# Load customer master data
customer_master = pd.read_csv("customer_master.csv")

# Merge customer details with cleaned feedback
final_df = pd.merge(
    df,
    customer_master,
    on="Customer_ID",
    how="left"
)

# Display the final dataset
final_df.head()

,Customer_ID,Customer_Name,Age,City,Rating,Feedback,Response_Channel,Email,Membership
0,1001,Aman Sharma,24.0,Delhi,5.0,Excellent service,Online,aman@gmail.com,Gold
1,1002,Priya Singh,29.0,Delhi,4.0,good service,Online,priya@gmail.com,Silver
2,1003,Rahul Kumar,31.5,Mumbai,4.0,No Feedback,Mobile App,rahul@gmail.com,Gold
3,1004,Simran Kaur,35.0,Mumbai,3.0,Average,Web,simran@gmail.com,Silver
4,1005,Karan Mehta,41.0,Chandigarh,5.0,Excellent,Unknown,karan@gmail.com,Gold

**Validate the Final Dataset**

**Check missing values**

In [70]:
# Check remaining missing values
final_df.isnull().sum()

Customer_ID         0
Customer_Name       0
Age                 0
City                0
Rating              0
Feedback            0
Response_Channel    0
Email               0
Membership          0
dtype: int64

**Check duplicates**

In [71]:
# Count duplicate rows
final_df.duplicated().sum()

np.int64(0)

In [72]:
# Check dimensions
# Display the final number of rows and columns
final_df.shape

(20, 9)

In [73]:
# Check data types
# Display the data types of all columns
final_df.dtypes

Customer_ID           int64
Customer_Name        object
Age                 float64
City                 object
Rating              float64
Feedback             object
Response_Channel     object
Email                object
Membership           object
dtype: object

**Save the Cleaned Dataset**

Once the data has been cleaned and merged, save it for future analysis.

In [74]:
# Save the final cleaned dataset as a CSV file
final_df.to_csv("cleaned_customer_feedback.csv", index=False)

# Display a confirmation message
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.