<a href="https://colab.research.google.com/github/Nihcas001/data_analysis_using_Python/blob/main/07(A)_Online_shopping_using_Pandas/online_shopping_using_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step 1 — Import Pandas**

Pandas is a Python library mainly used for data manipulation and analysis.

In [18]:
import pandas as pd  # Import Pandas library

**Why do we use Pandas?**

Pandas provides two important data structures:

**Series** → One-dimensional data

**DataFrame** → Two-dimensional tabular data

A DataFrame looks similar to an Excel table.

**Step 2 — Create the Dataset**

Let's create a dataset containing 15 customer orders.

In [19]:
# Create customer order data using a dictionary
data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005,
                 1006, 1007, 1008, 1009, 1010,
                 1011, 1012, 1013, 1014, 1015],

    "Customer": ["Aman", "Priya", "Rahul", "Simran", "Karan",
                 "Neha", "Arjun", "Riya", "Vikas", "Anjali",
                 "Mohit", "Pooja", "Rohit", "Sneha", "Varun"],

    "City": ["Delhi", "Mumbai", "Chandigarh", "Pune", "Delhi",
             "Jaipur", "Mumbai", "Chandigarh", "Bangalore", "Delhi",
             "Pune", "Mumbai", "Jaipur", "Delhi", "Bangalore"],

    "Product": ["Laptop", "Mobile", "Headphones", "Tablet", "Keyboard",
                "Monitor", "Mobile", "Mouse", "Laptop", "Tablet",
                "Headphones", "Laptop", "Mobile", "Monitor", "Keyboard"],

    "Category": ["Electronics", "Electronics", "Accessories", "Electronics",
                 "Accessories", "Electronics", "Electronics", "Accessories",
                 "Electronics", "Electronics", "Accessories", "Electronics",
                 "Electronics", "Electronics", "Accessories"],

    "Quantity": [1, 2, 1, 1, 2, 1, 1, 3, 1, 2, 2, 1, 2, 1, 2],

    "Price": [55000, 25000, 2000, 30000, 1500,
              18000, 27000, 800, 60000, 32000,
              2500, 58000, 24000, 20000, 1800],

    "Payment": ["UPI", "Card", "Cash", "UPI", "Card",
                "UPI", "Card", "Cash", "UPI", "Card",
                "UPI", "Card", "Cash", "UPI", "Card"],

    "Status": ["Delivered", "Delivered", "Pending", "Shipped", "Delivered",
               "Delivered", "Pending", "Delivered", "Shipped", "Delivered",
               "Cancelled", "Delivered", "Pending", "Shipped", "Delivered"]
}

# Convert the dictionary into a Pandas DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Card,Delivered
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
3,1004,Simran,Pune,Tablet,Electronics,1,30000,UPI,Shipped
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered
5,1006,Neha,Jaipur,Monitor,Electronics,1,18000,UPI,Delivered
6,1007,Arjun,Mumbai,Mobile,Electronics,1,27000,Card,Pending
7,1008,Riya,Chandigarh,Mouse,Accessories,3,800,Cash,Delivered
8,1009,Vikas,Bangalore,Laptop,Electronics,1,60000,UPI,Shipped
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered
10,1011,Mohit,Pune,Headphones,Accessories,2,2500,UPI,Cancelled
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered
12,1013,Rohit,Jaipur,Mobile,Electronics,2,24000,Cash,Pending
13,1014,Sneha,Delhi,Monitor,Electronics,1,20000,UPI,Shipped
14,1015,Varun,Bangalore,Keyboard,Accessories,2,1800,Card,Delivered

**Step 3 — Understand DataFrame Index**

Notice that Pandas automatically created an index:

In [20]:
# Display only the DataFrame index
df.index

RangeIndex(start=0, stop=15, step=1)

Important distinction

There are two different concepts:

`Index: 0, 1, 2, 3, ...`

`Order_ID: 1001, 1002, 1003, ...`

Order_ID is a column, while the default Pandas index is used to identify rows.

**Step 4 — Inspect the DataFrame**

In [21]:
# Display the first 5 rows
df.head()

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Card,Delivered
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
3,1004,Simran,Pune,Tablet,Electronics,1,30000,UPI,Shipped
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered

In [22]:
# Display the first 3 rows
df.head(3)

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Card,Delivered
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending

In [23]:
# Display the last 5 rows
df.tail()

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
10,1011,Mohit,Pune,Headphones,Accessories,2,2500,UPI,Cancelled
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered
12,1013,Rohit,Jaipur,Mobile,Electronics,2,24000,Cash,Pending
13,1014,Sneha,Delhi,Monitor,Electronics,1,20000,UPI,Shipped
14,1015,Varun,Bangalore,Keyboard,Accessories,2,1800,Card,Delivered

In [24]:
# Display the number of rows and columns
df.shape

(15, 9)

In [25]:
# Display all column names
df.columns

Index(['Order_ID', 'Customer', 'City', 'Product', 'Category', 'Quantity',
       'Price', 'Payment', 'Status'],
      dtype='object')

In [26]:
# Display DataFrame structure and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  15 non-null     int64
 1   Customer  15 non-null     object
 2   City      15 non-null     object
 3   Product   15 non-null     object
 4   Category  15 non-null     object
 5   Quantity  15 non-null     int64
 6   Price     15 non-null     int64
 7   Payment   15 non-null     object
 8   Status    15 non-null     object
dtypes: int64(3), object(6)
memory usage: 1.2+ KB

**Step 5 — Selecting a Single Column**

In [27]:
# Select the Customer column
print(df["Customer"])
print("\n\nThe result is a Pandas Series.")

0       Aman
1      Priya
2      Rahul
3     Simran
4      Karan
5       Neha
6      Arjun
7       Riya
8      Vikas
9     Anjali
10     Mohit
11     Pooja
12     Rohit
13     Sneha
14     Varun
Name: Customer, dtype: object


The result is a Pandas Series.

In [28]:
# Select the Customer column using dot notation
df.Customer

0       Aman
1      Priya
2      Rahul
3     Simran
4      Karan
5       Neha
6      Arjun
7       Riya
8      Vikas
9     Anjali
10     Mohit
11     Pooja
12     Rohit
13     Sneha
14     Varun
Name: Customer, dtype: object

This works in many cases, but the recommended approach is:

`df["Customer"]`

because it works reliably with column names containing spaces or special characters.

**Step 6 — Selecting Multiple Columns**

In [29]:
# Select multiple columns
df[["Customer", "Product", "Price"]]

   Customer     Product  Price
0      Aman      Laptop  55000
1     Priya      Mobile  25000
2     Rahul  Headphones   2000
3    Simran      Tablet  30000
4     Karan    Keyboard   1500
5      Neha     Monitor  18000
6     Arjun      Mobile  27000
7      Riya       Mouse    800
8     Vikas      Laptop  60000
9    Anjali      Tablet  32000
10    Mohit  Headphones   2500
11    Pooja      Laptop  58000
12    Rohit      Mobile  24000
13    Sneha     Monitor  20000
14    Varun    Keyboard   1800

Why double brackets?

Outer brackets:

`df[ ... ]`

tell Pandas that we are selecting data.

Inner brackets:

`["Customer", "Product", "Price"]`

contain the list of columns.

**Step 7 — Selecting Rows Using Indexing**

We can select rows based on their index.

**Select one row**

In [30]:
# Select the row with index 3
df.iloc[3]

Order_ID           1004
Customer         Simran
City               Pune
Product          Tablet
Category    Electronics
Quantity              1
Price             30000
Payment             UPI
Status          Shipped
Name: 3, dtype: object

**Step 8 — .iloc[] Indexing**

`.iloc[]` means integer-location based indexing.

It selects data using numerical positions.

**Select first row**

In [31]:
# Select the first row using its integer position
df.iloc[0]

Order_ID           1001
Customer           Aman
City              Delhi
Product          Laptop
Category    Electronics
Quantity              1
Price             55000
Payment             UPI
Status        Delivered
Name: 0, dtype: object

In [32]:
# Select the fifth row
df.iloc[4]

Order_ID           1005
Customer          Karan
City              Delhi
Product        Keyboard
Category    Accessories
Quantity              2
Price              1500
Payment            Card
Status        Delivered
Name: 4, dtype: object

In [33]:
# Select rows at positions 0, 2 and 4
df.iloc[[0, 2, 4]]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered

**Step 9 — Row Slicing Using .iloc[]**

In [34]:
# Select rows from position 1 to position 4, Excluded 5th position
df.iloc[1:5]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Card,Delivered
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
3,1004,Simran,Pune,Tablet,Electronics,1,30000,UPI,Shipped
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered

**Step 10 — Selecting Specific Rows and Columns Using .iloc[]**

Synatx:
`df.iloc[row_selection, column_selection]`

In [35]:
# Select rows 0 to 4 and columns 1 to 3
df.iloc[0:5, 1:4]

  Customer        City     Product
0     Aman       Delhi      Laptop
1    Priya      Mumbai      Mobile
2    Rahul  Chandigarh  Headphones
3   Simran        Pune      Tablet
4    Karan       Delhi    Keyboard

In [36]:
# Select specific rows and specific columns
# Select rows 0, 2 and 4 and columns 1 and 3
df.iloc[[0, 2, 4], [1, 3]]

  Customer     Product
0     Aman      Laptop
2    Rahul  Headphones
4    Karan    Keyboard

**Step 11 — .loc[] Indexing**

.loc[] is label-based indexing.

Syntax:

`df.loc[row_label, column_label]`

In [37]:
# Select the row having index label 3
df.loc[3]

Order_ID           1004
Customer         Simran
City               Pune
Product          Tablet
Category    Electronics
Quantity              1
Price             30000
Payment             UPI
Status          Shipped
Name: 3, dtype: object

In [38]:
# Select the customer from row label 3
df.loc[3, "Customer"]

'Simran'

**Step 12 — .loc[] for Multiple Columns**

In [39]:
# Select Customer, City and Product for row 3
df.loc[3, ["Customer", "City", "Product"]]

Customer    Simran
City          Pune
Product     Tablet
Name: 3, dtype: object

**Step 13 — .loc[] for Multiple Rows**

In [40]:
# Select rows from index 2 through index 5
df.loc[2:5]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
3,1004,Simran,Pune,Tablet,Electronics,1,30000,UPI,Shipped
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered
5,1006,Neha,Jaipur,Monitor,Electronics,1,18000,UPI,Delivered

**Important difference**

**With .loc[]:**

`df.loc[2:5]`

includes 5.

**With .iloc[]:**

`df.iloc[2:5]`

does not include position 5.

This is an important exam/interview concept.

In [41]:
df.loc[2:5] # includes 5

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
3,1004,Simran,Pune,Tablet,Electronics,1,30000,UPI,Shipped
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered
5,1006,Neha,Jaipur,Monitor,Electronics,1,18000,UPI,Delivered

In [42]:
df.iloc[2:5] # Not include 5

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
3,1004,Simran,Pune,Tablet,Electronics,1,30000,UPI,Shipped
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered

**Step 14 — .loc[] for Rows and Columns**

In [43]:
# Select rows 2 to 5 and only Customer and Product columns
df.loc[2:5, ["Customer", "Product"]]

  Customer     Product
2    Rahul  Headphones
3   Simran      Tablet
4    Karan    Keyboard
5     Neha     Monitor

**Step 15 — Conditional Selection**

Now we move to a very important real-world operation: **filtering**.


Suppose we want customers who purchased from Delhi.

In [44]:
# Select orders where the city is Delhi
df[df["City"] == "Delhi"]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered
13,1014,Sneha,Delhi,Monitor,Electronics,1,20000,UPI,Shipped

**Step 16 — Filter Orders Above ₹30,000**

In [45]:
# Select orders where the price is greater than 30000
df[df["Price"] > 30000]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
8,1009,Vikas,Bangalore,Laptop,Electronics,1,60000,UPI,Shipped
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered

**Step 17 — Filter Based on Multiple Conditions**

Suppose we want:

>Electronics products costing more than ₹30,000.

In [46]:
# Select electronics orders costing more than 30000
df[(df["Category"] == "Electronics") & (df["Price"] > 30000)]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
8,1009,Vikas,Bangalore,Laptop,Electronics,1,60000,UPI,Shipped
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered

**Important**

For multiple conditions, use: &
 for AND

and: | for OR

Do not use Python's normal:
and,
or

with Pandas Series.

**Step 18 — OR Condition**

Suppose we want orders from either Delhi or Mumbai.

In [47]:
# Select orders from Delhi or Mumbai
df[(df["City"] == "Delhi") | (df["City"] == "Mumbai")]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Card,Delivered
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered
6,1007,Arjun,Mumbai,Mobile,Electronics,1,27000,Card,Pending
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered
13,1014,Sneha,Delhi,Monitor,Electronics,1,20000,UPI,Shipped

**Step 19 — Filtering Using .loc[]**

We can combine .loc[] with conditions.

In [48]:
# Select Customer and Product for orders from Delhi
df.loc[df["City"] == "Delhi", ["Customer", "Product"]]

   Customer   Product
0      Aman    Laptop
4     Karan  Keyboard
9    Anjali    Tablet
13    Sneha   Monitor

This is particularly useful because we can **filter rows and select columns simultaneously.**

**Step 20 — Select Delivered Orders**

In [49]:
# Select all orders that have been delivered
df[df["Status"] == "Delivered"]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Card,Delivered
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered
5,1006,Neha,Jaipur,Monitor,Electronics,1,18000,UPI,Delivered
7,1008,Riya,Chandigarh,Mouse,Accessories,3,800,Cash,Delivered
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered
14,1015,Varun,Bangalore,Keyboard,Accessories,2,1800,Card,Delivered

**Step 21 — Select Pending Orders**

In [50]:
# Select orders that are still pending
df[df["Status"] == "Pending"]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Pending
6,1007,Arjun,Mumbai,Mobile,Electronics,1,27000,Card,Pending
12,1013,Rohit,Jaipur,Mobile,Electronics,2,24000,Cash,Pending

**Step 22 — Select Customers Who Bought Laptops**

In [51]:
# Select orders where the purchased product is a Laptop
df[df["Product"] == "Laptop"]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered
8,1009,Vikas,Bangalore,Laptop,Electronics,1,60000,UPI,Shipped
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered

**Step 23 — Changing a Value Using .loc[]**

Pandas also allows us to modify values.

Suppose order 1003 has been shipped.

In [52]:
# Change the status of order 1003 to Shipped
df.loc[df["Order_ID"] == 1003, "Status"] = "Shipped"

In [53]:
# Display the updated order
df[df["Order_ID"] == 1003]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Shipped

**Step 24 — Adding a New Column**

We can calculate the total order value.

Formula:

`Total Amount = Quantity × Price`

In [54]:
# Calculate total amount for each order
df["Total_Amount"] = df["Quantity"] * df["Price"]

# Display the updated DataFrame
df

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status,Total_Amount
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered,55000
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Card,Delivered,50000
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Cash,Shipped,2000
3,1004,Simran,Pune,Tablet,Electronics,1,30000,UPI,Shipped,30000
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Card,Delivered,3000
5,1006,Neha,Jaipur,Monitor,Electronics,1,18000,UPI,Delivered,18000
6,1007,Arjun,Mumbai,Mobile,Electronics,1,27000,Card,Pending,27000
7,1008,Riya,Chandigarh,Mouse,Accessories,3,800,Cash,Delivered,2400
8,1009,Vikas,Bangalore,Laptop,Electronics,1,60000,UPI,Shipped,60000
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered,64000
10,1011,Mohit,Pune,Headphones,Accessories,2,2500,UPI,Cancelled,5000
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered,58000
12,1013,Rohit,Jaipur,Mobile,Electronics,2,24000,Cash,Pending,48000
13,1014,Sneha,Delhi,Monitor,Electronics,1,20000,UPI,Shipped,20000
14,1015,Varun,Bangalore,Keyboard,Accessories,2,1800,Card,Delivered,3600

**Step 25 — Select Orders Based on Total Amount**

Now that we have calculated Total_Amount, we can use it for filtering.

In [55]:
# Select orders with total value greater than 50000
df[df["Total_Amount"] > 50000]

,Order_ID,Customer,City,Product,Category,Quantity,Price,Payment,Status,Total_Amount
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,UPI,Delivered,55000
8,1009,Vikas,Bangalore,Laptop,Electronics,1,60000,UPI,Shipped,60000
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Card,Delivered,64000
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Card,Delivered,58000

**Step 26 — Remove a Column**

Suppose we want to remove the Payment column.

In [56]:
# Remove the Payment column
df = df.drop("Payment", axis=1)

# Display the updated DataFrame
df

,Order_ID,Customer,City,Product,Category,Quantity,Price,Status,Total_Amount
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,Delivered,55000
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Delivered,50000
2,1003,Rahul,Chandigarh,Headphones,Accessories,1,2000,Shipped,2000
3,1004,Simran,Pune,Tablet,Electronics,1,30000,Shipped,30000
4,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Delivered,3000
5,1006,Neha,Jaipur,Monitor,Electronics,1,18000,Delivered,18000
6,1007,Arjun,Mumbai,Mobile,Electronics,1,27000,Pending,27000
7,1008,Riya,Chandigarh,Mouse,Accessories,3,800,Delivered,2400
8,1009,Vikas,Bangalore,Laptop,Electronics,1,60000,Shipped,60000
9,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Delivered,64000
10,1011,Mohit,Pune,Headphones,Accessories,2,2500,Cancelled,5000
11,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Delivered,58000
12,1013,Rohit,Jaipur,Mobile,Electronics,2,24000,Pending,48000
13,1014,Sneha,Delhi,Monitor,Electronics,1,20000,Shipped,20000
14,1015,Varun,Bangalore,Keyboard,Accessories,2,1800,Delivered,3600

Here:

`axis=1`

means we are removing a column.

For rows:

`axis=0`

**Step 27 — Reset the Index**

Sometimes after filtering, we may want to create a fresh sequential index.

In [57]:
# Filter delivered orders
delivered_df = df[df["Status"] == "Delivered"]

# Reset the index after filtering
delivered_df = delivered_df.reset_index(drop=True)

# Display the result
delivered_df

,Order_ID,Customer,City,Product,Category,Quantity,Price,Status,Total_Amount
0,1001,Aman,Delhi,Laptop,Electronics,1,55000,Delivered,55000
1,1002,Priya,Mumbai,Mobile,Electronics,2,25000,Delivered,50000
2,1005,Karan,Delhi,Keyboard,Accessories,2,1500,Delivered,3000
3,1006,Neha,Jaipur,Monitor,Electronics,1,18000,Delivered,18000
4,1008,Riya,Chandigarh,Mouse,Accessories,3,800,Delivered,2400
5,1010,Anjali,Delhi,Tablet,Electronics,2,32000,Delivered,64000
6,1012,Pooja,Mumbai,Laptop,Electronics,1,58000,Delivered,58000
7,1015,Varun,Bangalore,Keyboard,Accessories,2,1800,Delivered,3600

**Step 28 — A Practical Example**

Suppose the shopping platform asks:

>Find customers from Mumbai who purchased products costing more than ₹20,000.

We can solve it using:

In [58]:
# Filter Mumbai customers with products costing more than 20000
result = df.loc[
    (df["City"] == "Mumbai") & (df["Price"] > 20000),
    ["Customer", "Product", "Price", "Status"]
]

# Display the selected information
result

   Customer Product  Price     Status
1     Priya  Mobile  25000  Delivered
6     Arjun  Mobile  27000    Pending
11    Pooja  Laptop  58000  Delivered

This combines:

```
.loc[]
Boolean conditions
&
Multiple-column selection
```



This is a very realistic DataFrame operation.

**Step 29 — Another Practical Example**

Question:

>Display the Customer, Product and Total Amount for delivered orders.

In [59]:
# Select delivered orders and required columns
result = df.loc[
    df["Status"] == "Delivered",
    ["Customer", "Product", "Total_Amount"]
]

# Display the result
result

   Customer   Product  Total_Amount
0      Aman    Laptop         55000
1     Priya    Mobile         50000
4     Karan  Keyboard          3000
5      Neha   Monitor         18000
7      Riya     Mouse          2400
9    Anjali    Tablet         64000
11    Pooja    Laptop         58000
14    Varun  Keyboard          3600